name: Webtech back CI/CD
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # CI part
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-end
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: check
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: install dependency
        run: npm install
      - run: npm test
